before_install:
- openssl aes-256-cbc -K $encrypted_0064ee71e13a_key -iv $encrypted_0064ee71e13a_iv
  -in ssh-key.enc -out ssh-key -d
- sudo pip install -r requirements.txt
script: bash ./build.sh
sudo: required
