site_name: HSR Notizen HS17
site_url: https://doc.robinsuter.ch
repo_url: https://github.com/Excape/hsr-docs-hs17
site_description: HSR Study Documentation HS17
site_author: Robin Suter
copyright: 'Copyright (c) 2017 Robin Suter'

theme: 'material'

pages:
    - Home: 'index.md'
    - Playground: 'playground.md'
    - PrfM:
        - Index: 'prfm/index.md'
        - Introduction: 'prfm/introduction.md'
        - Formal Proof: 'prfm/formal_proof.md'
    - PmQm:
        - Index: 'pmqm/index.md'
        - Exam: 'pmqm/exam.md'
        - Projekt und Qualität: 'pmqm/projekt_qualitaet.md'
    - AppArch:
        - Index: 'apparch/index.md'
    - APF:
        - Index: 'apf/index.md'

markdown_extensions:
  - toc(permalink=true)
  - sane_lists
  - admonition
  - mdx_math
  - codehilite(linenums=true)
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.smartsymbols

extra:
    palette:
        primary: 'indigo'
        accent: 'pink'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    author:
        github: 'excape'
        twitter: 'robin_suter'

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_SVG

extra_css: [extra.css]
