site_name: HSR Notizen HS17
site_url: https://doc.robinsuter.ch
repo_url: https://github.com/Excape/hsr-docs-hs17
site_description: HSR Study Documentation HS17
site_author: Robin Suter
copyright: 'Copyright (c) 2017 Robin Suter'

theme: 'material'

pages:
    - Home: 'index.md'
    - Playground: 'playground.md'
    - PrfM:
        - Index: 'prfm/index.md'
        - Introduction: 'prfm/introdQuction.md'
        - Formal Proof: 'prfm/formal_proof.md'
        - Propositional Calculus: 'prfm/propositional_calculus.md'
        - Logical Programming Intro: 'prfm/logic_programming_intro.md'
        - Prolog Unification: 'prfm/prolog_unification.md'
        - Prolog Lists: 'prfm/prolog_lists.md'
        - Prolog Recursion: 'prfm/prolog-recursion.md'
        - Prolog Arithmetic: 'prfm/prolog_arithmetic.md'
    - PmQm:
        - Index: 'pmqm/index.md'
        - Exam: 'pmqm/exam.md'
        - Projekt und Qualität: 'pmqm/projekt_qualitaet.md'
        - Projekte: 'pmqm/projekte.md'
        - Finanzen: 'pmqm/finanzen.md'
    - AppArch:
        - Index: 'apparch/index.md'
        - Fundamentals: 'apparch/architecture_fundamentals.md'
        - Agile Architecture: 'apparch/agile_architecture.md'
        - Solution Strategy: 'apparch/solution_strategy.md'
        - Component Modeling: 'apparch/component_modeling.md'
        - Component Dynamics & Container Patterns: 'apparch/component_dynamics_container_patterns.md'
        - Tactic DDD & Architectural Coding Style: 'apparch/DDD_coding-style.md'
        - Exercises:
            - Exercise 1: 'apparch/exercises/ex1.md'
    - APF:
        - Index: 'apf/index.md'
        - Introduction: 'apf/intro.md'
        - GoF Revisited: 'apf/gof_revisited.md'
        - Beyond GoF: 'apf/beyond_gof.md'
        - Values: 'apf/values.md'
        - Reflection: 'apf/reflection.md'

markdown_extensions:
  - toc(permalink=true)
  - sane_lists
  - admonition
  - mdx_math
  - codehilite(linenums=true)
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.smartsymbols

extra:
    palette:
        primary: 'indigo'
        accent: 'pink'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    author:
        github: 'excape'
        twitter: 'robin_suter'

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_SVG

extra_css: [extra.css]
